---
title: "Turismo en España"
author: "Hugo , Pavlina y Anna"
date: "10 de Diciembre de 2020"
output:
  html_document:
    theme: paper
    highlight: textmate 
    toc: true
    toc_depth: 3 
    toc_float: 
      collapsed: true
      smooth_scroll: true
    self_contained: true
    number_sections: false
    df_print: kable
    code_download: true
editor_options: 
  chunk_output_type: console
---

```{r packages-setup, include = FALSE}
library(tidyverse)
library(klippy)  #- remotes::install_github("rlesur/klippy")
library(knitr)
```

```{r chunk-setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, 
                      #results = "hold",
                      cache = FALSE, cache.path = "/caches/", comment = "#>",
                      #fig.width = 7, #fig.height= 7,   
                      #out.width = 7, out.height = 7,
                      collapse = TRUE,  fig.show = "hold",
                      fig.asp = 7/9, out.width = "60%", fig.align = "center")
#- para mejorar los gráficos, bueno en realidad para que se vean igual en distintos SO
#- https://www.jumpingrivers.com/blog/r-knitr-markdown-png-pdf-graphics/
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"))
```

```{r options-setup, include = FALSE}
options(scipen = 999) #- para quitar la notación científica
options("yaml.eval.expr" = TRUE) #- https://github.com/viking/r-yaml/issues/47  (lo puse x el pb con el warning) En realidad creo que mejor sería ponerlo en RProfile
```


```{r klippy, echo = FALSE}
klippy::klippy(position = c("top", "right")) #- remotes::install_github("rlesur/klippy")
```

-----------------

<br>

Aquí empieza tu informe. Lo lógico es que empieces con una sección de Introducción o motivación o ....

## 1. Introducción

Este trabajo se centrará en el turismo en España, y principalmente en:

> - Origen de los turistas 
> - Motivos de su llegada
> - Gasto


## 2.  Datos

Los datos los hemos extraido del INE.es

## 3. Proceso
Para la realizacion de nuestro proyecto hemos seguido los siguientes pasos:


 
 >- 1. Descargar los datos de Ine.es en formato .csv
 >- 2. Subir los datos en **Github** para que desde allí se puedan importar y descargar
 




## 4. Rtdos


## 5. Conclusión

Las conclusiones son ...



## Referencias

Para la realización del trabajo he utilizado:

- Tutoriales del profesor Pedro

- Slides

- 


----------------

<br><br>

Para acabar este chunk para incluir tu `session info`:

```{r}
sessioninfo::session_info() %>% details::details(summary = 'current session info') 
```
